{% set name = "jupyterlab-favorites" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67be069a4fb120eedf0240b8503567e044fc6d9ee45ddf42098e1b605c1872e7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - jupyterlab >=3.1.0,<4.0.0
    - jupyter-packaging >=0.10.0,<2.0.0
  run:
    - python >=3.7

test:
  requires:
    - jupyterlab >=3.0.0,<4.0.0
  commands:
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/favorites.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-favorites
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Add the ability to save favorite folders to JupyterLab for quicker browsing.

extra:
  recipe-maintainers:
    - fcollonval
