{% set name = "jupyterlab-favorites" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5788898b859cc79e0717eeb801a156a0038ee5ce7b8bca8eeb2c19bd8b554f04

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  requires:
    - jupyterlab >=4.0.0,<5.0.0
    - python {{ python_min }}
  commands:
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/favorites.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-favorites
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Add the ability to save favorite folders to JupyterLab for quicker browsing.

extra:
  recipe-maintainers:
    - fcollonval
